### ISSUE TITLE
Veranderingen searchbar (styling)

### ISSUE THREAD

**Issue by RukiyaTossou** [RukiyaTossou/component-building-block#2]
-  Border toegevoegd,  zou ook een border shadow kunnen zijn maar dat is minder goed zichtbaar 
-  De tekst is lichter ,  licht grijs inplaats van zwart. Dit kan nog worden veranderd als het nodig is 
-  font moet worden aangepast

![image](https://github.com/user-attachments/assets/4864a497-14c4-4d1d-aeda-d3299a389d8f)

**Comment by RukiyaTossou** [comment]
Wat heb ik veranderd ?

- De unerline heb ik gemaakt met ::after, deze moet voor de zoek knop moet de lijn stoppen .  
- De tekst heb ik naar upper case gezet,  maar als de gebruiker gaat zoeken dan is de tekst in lowercase.  Ook ik de tekst wat dikker, dit komt overeen met mijn ontwerp. 
- De search bar heeft nu een goede breedte 
-  Er is een zoom toegevoegd op de search button bij een hover. 

![image](https://github.com/user-attachments/assets/f37ba09d-ea9e-43a8-b664-aa7acc2b5161)


```css

.search::after {
    content: '';
    position: absolute;	
    bottom: 0.5em;
    left: 0.5rem;
    width: 93%;
    height: 1px; 
    background-color: black;
}
```

Wat wil ik nog toevoegen?

- [ ] Een loading state toevoegen
