### ISSUE TITLE
(Horizonal scrol) images op het canvas hebben geen focus 

### ISSUE THREAD

**Issue by RukiyaTossou** [RukiyaTossou/component-building-block#3]
De slider zelf heeft geen focus en de images ook niet.  
Even kijken hoe dat het beste kan en of het er goed uit ziet

**Comment by RukiyaTossou** [comment]
```css
	.masonry-item:focus {
  outline: 2px solid #020202; 
  outline-offset: 3px; 
} 
```
